(global-set-key (kbd "<f4>") 'kill-buffer)
(global-set-key (kbd "<f5>") 'smart-compile)
(global-set-key (kbd "<f6>") 'es-git-status)
(global-set-key (kbd "<f7>") '(lambda ()
				(interactive)
				(compile "make")))
;;(global-set-key (kbd "<f9>") 'es-code2html-for-paste)
(global-set-key (kbd "<f10>") 'wb-line-number-toggle)
(global-set-key (kbd "<f12>") 'menu-bar-open)

(global-set-key (kbd "C-S-v") 'scroll-other-window)
(global-set-key (kbd "M-V") 'scroll-other-window-down)
(global-set-key (kbd "C-x nb") 'rename-buffer)
(global-set-key (kbd "M-/") 'hippie-expand)
(global-set-key (kbd "S-SPC") 'set-mark-command)
(global-set-key (kbd "C-S-s") 'isearch-forward-regexp)
(global-set-key (kbd "C-S-r") 'isearch-backward-regexp)
(global-set-key (kbd "C-%") 'query-replace-regexp)
(global-set-key (kbd "M-h") 'backward-kill-word)
(global-set-key (kbd "C-M-h") 'backward-kill-sentence)
(global-set-key (kbd "C-x C-u") 'undo)
(global-set-key (kbd "C-x C-k") 'kill-buffer)
